dict1={"name":"Paul Wesley", "Age":39 , "Series":"The Vampire Diaries", "known as":"Stefan Salvatore", "Height":"1.8m"}
print("keys..................",dict1.keys())
print("items.................",dict1.items())
print("values................",dict1.values())
dict2 = dict1.copy()
print("copy..................",dict2)
print("get...................",dict1.get("name"))
dict1.pop("Age")
print("pop...................",dict1)
dict1.popitem()
print("popitem...............",dict1)
print("setdefault............",dict1.setdefault("Series"))
dict1.update({"dob":"23 July 1982"})
print("update................",dict1)
